version: "3.7"

services:
  app:

  database:
    container_name: database
    image: mysql:8.0.19
    env_file:
      - ../mysql.env
    networks: 
      - database_net
    ports: 
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
      - ../init.db:/docker-entrypoint-initdb.d
    command: --default_authentication_plugin=mysql_native_password
  
  adminer:
    container_name: adminer
    image: dehy/adminer
    networks: 
      - database_net
    ports: 
      - 8080:80


networks: 
  database_net:
    driver: bridge

volumes:
  database_data:
