version: "3.7"

services:
    flask:
        build: ./flask
        container_name: fastimmo_flask
        restart: always
        environment:
            - APP_NAME=FastImmo
        expose:
            - 8080

    nginx:
        build: ./nginx
        container_name: fastimmo_nginx
        restart: always
        ports:
            - "8080:80"
